// BudgetTrackerAi/src/constants/categories.ts
import { MaterialIcons } from '@expo/vector-icons';
import { BudgetCategory } from '@/types/finance';

export const CATEGORY_CONFIG: Record<
    BudgetCategory,
    { color: string; icon: keyof typeof MaterialIcons.glyphMap }
> = {
    'Food & Dining': { color: '#EF4444', icon: 'restaurant' },
    'Transportation': { color: '#3B82F6', icon: 'directions-car' },
    'Housing': { color: '#10B981', icon: 'home' },
    'Utilities': { color: '#F59E0B', icon: 'lightbulb' },
    'Entertainment': { color: '#8B5CF6', icon: 'movie' },
    'Shopping': { color: '#EC4899', icon: 'shopping-cart' },
    'Salary': { color: '#059669', icon: 'account-balance' },
    'Investment Income': { color: '#047857', icon: 'trending-up' },
    'Healthcare': { color: '#DC2626', icon: 'medical-services' },
    'Education': { color: '#7C3AED', icon: 'school' },
    'Travel': { color: '#06B6D4', icon: 'flight' },
    'Insurance': { color: '#475569', icon: 'security' },
    'Groceries': { color: '#F97316', icon: 'shopping-basket' },
    'Dining Out': { color: '#D97706', icon: 'local-dining' },
    'Public Transport': { color: '#2563EB', icon: 'directions-bus' },
    'Fuel': { color: '#1E40AF', icon: 'local-gas-station' },
    'Rent': { color: '#16A34A', icon: 'apartment' },
    'Mortgage': { color: '#15803D', icon: 'house' },
    'Electricity': { color: '#D97706', icon: 'bolt' },
    'Water': { color: '#0284C7', icon: 'water-drop' },
    'Internet': { color: '#7E22CE', icon: 'wifi' },
    'Phone': { color: '#6D28D9', icon: 'phone' },
    'Movies & Shows': { color: '#A21CAF', icon: 'theater-comedy' },
    'Clothing': { color: '#DB2777', icon: 'checkroom' },
    'Electronics': { color: '#374151', icon: 'devices' },
    'Freelance Income': { color: '#0D9488', icon: 'work' },
    'Bonus': { color: '#14B8A6', icon: 'card-giftcard' },
    'Medical Expenses': { color: '#B91C1C', icon: 'local-hospital' },
    'Tuition': { color: '#6B21A8', icon: 'book' },
    'Books & Supplies': { color: '#5B21B6', icon: 'menu-book' },
    'Vacation': { color: '#0E7490', icon: 'beach-access' },
    'Flights': { color: '#155E75', icon: 'airplanemode-active' },
    'Car Insurance': { color: '#4B5563', icon: 'directions-car-filled' },
    'Health Insurance': { color: '#6B7280', icon: 'health-and-safety' },
    'Miscellaneous': { color: '#4B5563', icon: 'category' },
};

export const CATEGORIES = [
    'Food & Dining',
    'Transportation',
    'Housing',
    'Utilities',
    'Entertainment',
    'Shopping',
    'Salary',
    'Investment Income',
    'Healthcare',
    'Education',
    'Travel',
    'Insurance',
    'Groceries',
    'Dining Out',
    'Public Transport',
    'Fuel',
    'Rent',
    'Mortgage',
    'Electricity',
    'Water',
    'Internet',
    'Phone',
    'Movies & Shows',
    'Clothing',
    'Electronics',
    'Freelance Income',
    'Bonus',
    'Medical Expenses',
    'Tuition',
    'Books & Supplies',
    'Vacation',
    'Flights',
    'Car Insurance',
    'Health Insurance',
    'Miscellaneous',
] as const;