// backend/src/constants/categories.ts
export const CATEGORIES = [
    'Food & Dining',
    'Transportation',
    'Housing',
    'Utilities',
    'Entertainment',
    'Shopping',
    'Salary',
    'Investment Income',
    'Healthcare',
    'Education',
    'Travel',
    'Insurance',
    'Groceries',
    'Dining Out',
    'Public Transport',
    'Fuel',
    'Rent',
    'Mortgage',
    'Electricity',
    'Water',
    'Internet',
    'Phone',
    'Movies & Shows',
    'Clothing',
    'Electronics',
    'Freelance Income',
    'Bonus',
    'Medical Expenses',
    'Tuition',
    'Books & Supplies',
    'Vacation',
    'Flights',
    'Car Insurance',
    'Health Insurance',
    'Miscellaneous',
] as const;

export type Category = typeof CATEGORIES[number];